import { FullFormSchema } from '@/types/schema';

export const SAMPLE_FORMS: FullFormSchema[] = [
  {
    id: 'quiz-web-dev',
    title: 'Kuis Pemrograman Web & JavaScript Modern 2026',
    description: 'Uji pemahaman Anda seputar konsep dasar JavaScript ES2026, React 19, arsitektur web modern, dan Tailwind CSS. Setiap soal memiliki bobot poin dan kunci jawaban otomatis.',
    submitButtonText: 'Kirim Jawaban Kuis',
    theme: {
      primaryColor: '#673ab7',
      accentColor: '#673ab7',
      backgroundColor: '#f0ebf8',
      fontFamily: 'sans',
      borderRadius: 'md',
    },
    settings: {
      isQuiz: true,
      releaseGradesImmediately: true,
      showMissedQuestions: true,
      showCorrectAnswers: true,
      showPointValues: true,
      defaultQuestionPoints: 25,
      collectEmail: true,
      limitOneResponse: false,
      allowResponseEditing: false,
      isAcceptingResponses: true,
      showProgressBar: true,
      shuffleQuestions: false,
      confirmationMessage: 'Jawaban kuis Anda telah berhasil dikirim! Silakan klik tombol "Lihat Skor" untuk melihat nilai dan pembahasan lengkap.',
      showSubmitAnotherLink: true,
    },
    sections: [
      {
        id: 'sec-1',
        title: 'Bagian 1: Konsep Fundamental & Teori',
        description: 'Jawablah pertanyaan pilihan ganda berikut dengan memilih satu jawaban yang paling tepat.',
        afterSectionAction: 'next',
      },
      {
        id: 'sec-2',
        title: 'Bagian 2: Analisis Kode & Sintaksis',
        description: 'Pilihlah semua jawaban yang benar atau isikan jawaban singkat.',
        afterSectionAction: 'submit',
      },
    ],
    questions: [
      {
        id: 'q-1',
        sectionId: 'sec-1',
        type: 'radio',
        title: 'Manakah dari pernyataan berikut yang paling tepat mengenai perbedaan antara "let" dan "const" di JavaScript?',
        description: 'Pilih satu jawaban yang paling benar.',
        required: true,
        options: [
          { id: 'opt-1', label: '"let" memiliki cakupan fungsi (function scope), sedangkan "const" block scope', value: 'opt-1' },
          { id: 'opt-2', label: 'Variabel dengan "let" dapat di-reassign nilainya, sedangkan "const" tidak dapat di-reassign', value: 'opt-2' },
          { id: 'opt-3', label: '"const" membuat seluruh isi objek dan array menjadi immutable secara otomatis', value: 'opt-3' },
          { id: 'opt-4', label: 'Keduanya identik dan hanya berbeda penamaan gaya penulisan', value: 'opt-4' },
        ],
        quiz: {
          points: 25,
          correctAnswers: ['opt-2'],
          explanation: '"let" memungkinkan reassignment nilai baru, sedangkan identifier "const" terikat tetap pada referensinya (tidak dapat di-reassign dengan operator =). Namun properti objek di dalam const tetap dapat diubah kecuali dibekukan dengan Object.freeze.',
        },
      },
      {
        id: 'q-2',
        sectionId: 'sec-1',
        type: 'radio',
        title: 'Apa fungsi utama dari hook `useMemo` pada React?',
        required: true,
        options: [
          { id: 'opt-2a', label: 'Menyimpan nilai kalkulasi komputasi berat agar tidak dihitung ulang di setiap re-render', value: 'opt-2a' },
          { id: 'opt-2b', label: 'Melakukan side-effect seperti pemanggilan API asynchronous', value: 'opt-2b' },
          { id: 'opt-2c', label: 'Memaksa komponen untuk melakukan render ulang saat state global berubah', value: 'opt-2c' },
          { id: 'opt-2d', label: 'Menggantikan fungsi localStorage browser', value: 'opt-2d' },
        ],
        quiz: {
          points: 25,
          correctAnswers: ['opt-2a'],
          explanation: 'useMemo digunakan untuk memoisasi hasil kalkulasi yang memerlukan biaya komputasi tinggi sehingga hanya dihitung ulang saat dependensinya berubah.',
        },
      },
      {
        id: 'q-3',
        sectionId: 'sec-2',
        type: 'checkbox',
        title: 'Manakah di antara teknologi berikut yang termasuk library CSS / styling modern? (Pilih semua yang sesuai)',
        description: 'Soal ini memiliki lebih dari satu jawaban benar.',
        required: true,
        options: [
          { id: 'opt-3a', label: 'Tailwind CSS', value: 'opt-3a' },
          { id: 'opt-3b', label: 'PostgreSQL', value: 'opt-3b' },
          { id: 'opt-3c', label: 'CSS Modules', value: 'opt-3c' },
          { id: 'opt-3d', label: 'Docker Compose', value: 'opt-3d' },
        ],
        quiz: {
          points: 25,
          correctAnswers: ['opt-3a', 'opt-3c'],
          explanation: 'Tailwind CSS dan CSS Modules adalah teknik & pustaka styling CSS modern. PostgreSQL adalah database RDBMS dan Docker adalah platform kontainerisasi.',
        },
      },
      {
        id: 'q-4',
        sectionId: 'sec-2',
        type: 'text',
        title: 'Tuliskan nama metode JavaScript bawaan pada Array untuk menyaring elemen berdasarkan kondisi logika tertentu:',
        placeholder: 'contoh: map, forEach, dll.',
        required: true,
        quiz: {
          points: 25,
          correctAnswers: ['filter', 'filter()', 'Array.prototype.filter'],
          explanation: 'Metode Array.prototype.filter() mengembalikan array baru berisi seluruh elemen yang lolos uji pengujian fungsi predikat callback.',
        },
      },
    ],
    responses: [
      {
        id: 'resp-1',
        submittedAt: '2026-09-21T14:20:00.000Z',
        email: 'ahmad.fauzi@example.com',
        answers: {
          'q-1': 'opt-2',
          'q-2': 'opt-2a',
          'q-3': ['opt-3a', 'opt-3c'],
          'q-4': 'filter',
        },
        quizScore: {
          totalPoints: 100,
          maxPoints: 100,
          breakdown: {
            'q-1': { earned: 25, max: 25, isCorrect: true },
            'q-2': { earned: 25, max: 25, isCorrect: true },
            'q-3': { earned: 25, max: 25, isCorrect: true },
            'q-4': { earned: 25, max: 25, isCorrect: true },
          },
        },
      },
    ],
  },
  {
    id: 'survey-satisfaction',
    title: 'Survei Kepuasan Pengguna & Evaluasi Layanan Digital',
    description: 'Masukan berharga Anda membantu kami terus meningkatkan kualitas platform. Pengisian survei membutuhkan waktu kurang dari 3 menit.',
    submitButtonText: 'Kirim Masukan',
    theme: {
      primaryColor: '#009688',
      accentColor: '#009688',
      backgroundColor: '#e0f2f1',
      fontFamily: 'sans',
      borderRadius: 'md',
    },
    settings: {
      isQuiz: false,
      releaseGradesImmediately: false,
      showMissedQuestions: false,
      showCorrectAnswers: false,
      showPointValues: false,
      defaultQuestionPoints: 0,
      collectEmail: false,
      limitOneResponse: false,
      allowResponseEditing: true,
      isAcceptingResponses: true,
      showProgressBar: false,
      shuffleQuestions: false,
      confirmationMessage: 'Terima kasih banyak atas partisipasi dan penilaian Anda dalam survei ini!',
      showSubmitAnotherLink: true,
    },
    sections: [
      {
        id: 'sec-main',
        title: 'Formulir Survei Kepuasan',
        description: 'Berikan penilaian sejujurnya berdasarkan pengalaman nyata Anda.',
        afterSectionAction: 'submit',
      },
    ],
    questions: [
      {
        id: 'sq-1',
        sectionId: 'sec-main',
        type: 'scale',
        title: 'Secara keseluruhan, seberapa puaskah Anda dengan kecepatan performa aplikasi?',
        required: true,
        scaleMin: 1,
        scaleMax: 5,
        scaleMinLabel: 'Sangat Tidak Puas',
        scaleMaxLabel: 'Sangat Puas',
      },
      {
        id: 'sq-2',
        sectionId: 'sec-main',
        type: 'grid_radio',
        title: 'Evaluasi aspek-aspek antarmuka dan kemudahan navigasi berikut:',
        required: true,
        rows: [
          { id: 'r1', label: 'Kemudahan menemukan fitur' },
          { id: 'r2', label: 'Kejelasan teks & instruksi' },
          { id: 'r3', label: 'Kenyamanan tampilan visual' },
        ],
        columns: [
          { id: 'c1', label: 'Kurang' },
          { id: 'c2', label: 'Cukup' },
          { id: 'c3', label: 'Baik' },
          { id: 'c4', label: 'Sangat Baik' },
        ],
      },
    ],
    responses: [],
  },
];

